name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: pipx install uv
      - name: Sync deps
        run: uv sync --dev
      - name: Ruff
        run: uv run ruff check
      - name: Pytest
        run: uv run pytest -q

  examples:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: pipx install uv
      - name: Sync deps
        run: uv sync --dev
      - name: Run examples (smoke)
        run: |
          set -e
          uv run python examples/01_quickstart_sync.py
          uv run python examples/02_queries.py
          uv run python examples/03_relationships.py

