name: Lint and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Install package
        run: uv pip install -e .

      - name: Run Ruff (linting)
        run: uv run ruff check .

      - name: Run Ruff (formatting check)
        run: uv run ruff format --check .

      - name: Run tests
        run: uv run pytest
